server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: ecommerce
    password: ecommerce1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: my-super-secret-key-for-jwt-signing-must-be-long-enough-256bits
  access-token-expiration: 1800000    # 30분 (ms)
  refresh-token-expiration: 604800000 # 7일 (ms)
